ListAllOrder:
    path: /order/dropshipping
    controller: App\Infrastructure\Controller\DropShippingOrderController::listAll

ListAllPaidOrderredirect:
    path: /order/dropshippingpaid
    controller: App\Infrastructure\Controller\DropShippingOrderController::listAllPaidStatusByPage
    defaults:
        page: 1

ListAllPaidOrder:
    path: /order/dropshippingpaid/{page}/pg
    controller: App\Infrastructure\Controller\DropShippingOrderController::listAllPaidStatusByPage
    defaults:
        page: 1

listOneByOrderNumber:
    path: /order/dropshipping/{orderNumber}
    controller: App\Infrastructure\Controller\DropShippingOrderController::listOneByOrderNumber

listByOrderNumberAndArticle:
    path: /order/dropshipping/order/{orderNumber}/article/{article}
    controller: App\Infrastructure\Controller\DropShippingOrderController::listByOrderNumberAndArticle
    methods: [GET]

resetByOrderNumberAndArticle:
    path: /order/dropshipping/order/{orderNumber}/article/{article}/reset
    controller: App\Infrastructure\Controller\DropShippingOrderController::resetByOrderNumberAndArticle

NewProviderByNewProviderOrderNumberAndArticle:
    path: /order/dropshipping/order/{orderNumber}/article/{article}
    controller: App\Infrastructure\Controller\DropShippingOrderController::changeProvider
    methods: [POST]
