order_status_paid_out:
    path: /order/dropshipping
    controller: Javier\Exam\Infrastructure\Controller\Order\DropShippingOrder::showOrdersPaidOut

order_get_by_id:
    path: /order/dropshipping/{id}
    controller: Javier\Exam\Infrastructure\Controller\Order\DropShippingOrder::showOrderById
