#index:
#    path: /
#    controller: App\Controller\DefaultController::index

rellena:
    path: /rellena
    controller: App\Controller\ExamController::rellena

exercise1:
    path: /order/dropshipping
    controller: App\Controller\ExamController::returnPaidOrders

exercise2:
    path: /order/dropshipping/{order}/article/{article}/reset
    controller: App\Controller\ExamController::reset

exercise3:
    path: /order/dropshipping/{order}
    controller: App\Controller\ExamController::returnOrder
    requirements:
               order: '\d+'

exercise4:
    path: /order/dropshipping/{order}/article/{article}
    controller: App\Controller\ExamController::updateProvider
    requirements:
               provider: '\d+'

paginateex1:
   path: /order/dropshipping/paginateEx1/{page}
   controller: App\Controller\ExamController::paginateEx1
   defaults: { page: 1 }
   requirements:
           page: '\d+'


