#index:
#    path: /
#    controller: App\Controller\DefaultController::index
getAllOrders:
    path: /drop
    controller: App\examen\Infrastructure\Domain\Model\Controller\DropShipingController::getAllOrders