#index:
#    path: /
#    controller: App\Controller\DefaultController::index

allOrdersPaid:
    path: /dropshipping
    controller: App\Infrastructure\Controller\DropShippingContoller::allOrdersPaid
    methods: [POST]
