#index:
#    path: /
#    controller: App\Controller\DefaultController::index

allOrdersPaid:
    path: /order/dropshipping
    controller: App\Infrastructure\Controller\DropShippingController::allOrdersPaid
    methods: [GET]
